on:
  - push
  - pull_request
name: build
jobs:
  linux:
    name: build - Linux
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    timeout-minutes: 15
    strategy:
      matrix:
        ghcVersion:
          - '9.10.1'
          - '9.8.2'
          - '9.6.6'
          - '9.4.8'
        compiledMethod:
          - 'stack build --no-install-ghc --system-ghc'
          - 'cabal build'
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghcVersion }}
      - run: ${{ matrix.compiledMethod }}




# name: build
# on:
#   - push
#   - pull_request
# jobs:
#   linux:
#     name: build - Linux
#     runs-on: ubuntu-20.04
#     timeout-minutes: 15
#     container: haskell:9.8.2
#     # strategy:
#     #   matrix:
#     #     include:
#     #       - image: 
#     #       - image: haskell:9.6.5
#     steps:
#       - name: build
#         run: |
#           stack build --no-install-ghc --system-ghc --stack-root ${GITHUB_WORKSPACE}/.stack
