on:
  - push
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        ghcVersion:
          - '9.10.1'
          - '9.8.2'
          - '9.6.6'
          - '9.4.8'
        tool:
          - 'ghc'
          - 'cabal'
          - 'stack'
        include:
          - os: ubuntu-latest
            echoQuitReplCmd: 'echo ":q"'
            checkInterpreter: 'tee /dev/stderr | grep -q Ok'
          - os: windows-latest
            echoQuitReplCmd: 'Write-Output ":q"'
            checkInterpreter: 'Tee-Object -Variable Result; $Result | findstr Ok'
          - tool: ghc
            compile: 'ghc ./src/Lib.hs'
            interpret: 'ghci ./src/Lib.hs'
            haddock: 'haddock ./src/Lib.hs'
          - tool: cabal
            compile: 'cabal build'
            interpret: 'cabal repl'
            haddock: 'cabal haddock'
          - tool: stack
            compile: 'stack build --no-install-ghc --system-ghc'
            interpret: 'stack repl --no-install-ghc --system-ghc'
            haddock: 'stack haddock --no-install-ghc --system-ghc'
      fail-fast: false 
    uses: ./.github/workflows/does-it-compile.yml
    with:
      os: ${{ matrix.os }}
      echoQuitReplCmd: ${{ matrix.echoQuitReplCmd }}
      checkInterpreter: ${{ matrix.checkInterpreter }}
      ghcVersion: ${{ matrix.ghcVersion }}
      compile: ${{ matrix.compile }}
      interpret: ${{ matrix.interpret }}
      haddock: ${{ matrix.haddock }}
