on:
  - push
  - pull_request
name: build
jobs:
  linux:
    name: "Linux"
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    timeout-minutes: 15
    strategy:
      matrix:
        ghcVersion:
          - '9.10.1'
          - '9.8.2'
          - '9.6.6'
          - '9.4.8'
        compiledMethod:
          - 'ghc ./src/Lib.hs'
          - 'ghci ./src/Lib.hs <<< ":q" | tee /dev/stderr | grep -q Ok'
          - 'haddock ./src/Lib.hs'
          - 'cabal build'
          - 'cabal repl <<< ":q" | tee /dev/stderr | grep -q Ok'
          - 'cabal build && cabal repl <<< ":q" | tee /dev/stderr | grep -q Ok'
          - 'cabal haddock'
          - 'stack build --no-install-ghc --system-ghc'
          - 'stack repl --no-install-ghc --system-ghc <<< ":q" | tee /dev/stderr | grep -q Ok'
          - 'stack haddock --no-install-ghc --system-ghc'
      fail-fast: false 
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghcVersion }}
      - run: |
          echo "resolver: ghc-${{ matrix.ghcVersion }}" > stack.yaml
      - run: |
          echo "with-compiler: ghc-${{ matrix.ghcVersion }}" >> cabal.project
      - run: ${{ matrix.compiledMethod }}


  windows:
    name: "Windows"
    runs-on: windows-latest
    timeout-minutes: 15
    strategy:
      matrix:
        ghcVersion:
          - '9.10.1'
          - '9.8.2'
          - '9.6.6'
          - '9.4.8'
        compiledMethod:
          - 'cabal build'
          - 'Write-Output ":q" | cabal repl | Tee-Object -Variable Result; $Result | findstr Ok'
          - 'cabal build ; if($?) { Write-Output ":q" | cabal repl | Tee-Object -Variable Result; $Result | findstr Ok }'
      fail-fast: false 
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghcVersion }}
      - run: |
          echo "resolver: ghc-${{ matrix.ghcVersion }}" > stack.yaml
      - run: |
          echo "with-compiler: ghc-${{ matrix.ghcVersion }}" >> cabal.project
      - run: ${{ matrix.compiledMethod }}